name: "Inclui comentário"
description: "Inclui um comentário em uma issue ou pull request do GitHub."
author: "Lucas Lima"
inputs:
  GH_TOKEN:
    description: "Token de autenticação do GitHub."
    required: true
  issue-id:
    description: "ID da issue ou pull request onde o comentário será adicionado."
    required: true
  comment:
    description: "O comentário a ser adicionado."
    required: true
  GH_REPOSITORY:
    description: "Id do repositório"
    required: true
outputs:
  comment-id:
    description: "ID do comentário adicionado."
branding:
  icon: 'archive'
  color: 'gray-black'
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - '${{ inputs.GH_TOKEN }}'
    - '${{ inputs.issue-id }}'
    - '${{ inputs.comment }}'
    - '${{ inputs.GH_REPOSITORY }}'
